#springfox.documentation.swagger.v2.path=/api-docs
server.contextPath=/eims
server.port=9100
server.session.cookie.path=/
server.sessionTimeout=
server.session.cookie.http-only=true
server.session.cookie.secure=true

########## WAS Deploy ##########################
#local
spring.eims.datasource.url=jdbc:mysql://tvops-umy-dbs01:13306/DB_OPSEIM
spring.eims.datasource.username=EIM_APP
spring.eims.datasource.password=Oeimapp70()
spring.eims.datasource.driver-class-name=com.mysql.jdbc.Driver

#server
#spring.eims.datasource.jndi-name=java:/EIMSNXA

spring.eims.datasource.max-active=20
spring.eims.datasource.max-idle=20
spring.eims.datasource.min-idle=5

#local
#spring.meta.datasource.url=jdbc:mysql://10.244.106.114:13306/DB_OPSEIM
#spring.meta.datasource.username=eims
#spring.meta.datasource.password=eims
#spring.meta.datasource.driver-class-name=org.mysql.jdbc.Driver

#server
#spring.meta.datasource.jndi-name=java:/EIMSNXA

#spring.meta.datasource.max-active=20
#spring.meta.datasource.max-idle=20
#spring.meta.datasource.min-idle=5
########## Jeus Deploy ##########################



########## Jeus Deploy ##########################
#spring.eims.datasource.jndi-name=IEIM
#spring.eims.datasource.max-active=20
#spring.eims.datasource.max-idle=20
#spring.eims.datasource.min-idle=5
#
#spring.meta.datasource.jndi-name=META
#spring.meta.datasource.max-active=20
#spring.meta.datasource.max-idle=20
#spring.meta.datasource.min-idle=5
########## Jeus Deploy ##########################

spring.datasource.initial-size=10 
spring.datasource.validation-query= 
spring.datasource.test-on-borrow=false 
spring.datasource.test-on-return=false 
spring.datasource.test-while-idle= 
spring.datasource.time-between-eviction-runs-millis= 
spring.datasource.min-evictable-idle-time-millis= 
spring.datasource.max-wait=

# MULTIPART (MultipartProperties)
spring.http.multipart.enabled=true
spring.http.multipart.max-file-size=1Mb
spring.http.multipart.max-request-size=10Mb


# MyBatis Config
mybatis.mapper-locations=classpath:eims/web/dao/xml/*

#messages
spring.messages.encoding=UTF-8
#schedule
#schedule.test2=0 23 14 * * *

#option
#statistics.run=false
#bx.config.test1=10


spring.http.encoding.charset=UTF-8
