### MESSAGE PROPERTIES
#message.locale=en
message.locale=ko
default.roleId=Developer
admin.roleId=Administrator
excelexport.dir=/data/pjsrc/eim/
# Users
crypto.key=2f88ba962b490935
deploy.readtimeout=10
deploy.conntimeout=3
